name: cd

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      -
        name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: 'go.mod'
          cache: false
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        with:
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: 'latest'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAPS_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAPS_GITHUB_TOKEN }}
      -
        name: Get tag without 'v' prefix
        run: echo "SNP_CLI_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      -
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0 # zizmor: ignore[cache-poisoning] setup-node@v4 does not cache unless the cache input is set
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISHING_AUTOMATION_TOKEN }}
        with:
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'
      -
        name: Publish npm packages
        run: cd npm && version="$SNP_CLI_VERSION" ./create-platform-packages.sh
