name: cd

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '2.2.0'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAPS_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAPS_GITHUB_TOKEN }}
      -
        name: Get tag without 'v' prefix
        run: echo "SNP_CLI_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      -
        name: Publish npm packages
        uses: actions/setup-node@v4
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISHING_AUTOMATION_TOKEN }}
        with:
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'
        run: cd npm && version="$SNP_CLI_VERSION" ./create-platform-packages.sh
