name: Download and validate
on:
  schedule:
    - cron: '0 0 * * SUN'  # Runs every Monday at noon UTC
  pull_request:
    branches:
      - main
      - develop
jobs:
  download-and-validate:
    runs-on: ubuntu-latest
    env:
      SNOWPLOW_CONSOLE_API_KEY_ID: ${{ secrets.SNP_ENGINEERING_KEY_ID }}
      SNOWPLOW_CONSOLE_API_KEY: ${{ secrets.SNP_ENGINEERING_KEY }}
      SNOWPLOW_CONSOLE_ORG_ID: ${{ secrets.SNP_ENGINEERING_ORG_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: download ds
        run: go run main.go ds download && go run main.go ds download --output-format json
      - name: validate ds
        run: go run main.go ds validate
      - name: download dp
        run: go run main.go dp download && go run main.go dp download --output-format json
      - name: validate dp
        run: go run main.go dp validate

